spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: kumar53shubham@gmail.com
    password: snhuomxztjfefkyt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
